export const THE_PLACE_ABI = [
	{
		inputs: [
			{ name: "companyUrl", type: "string" },
			{ name: "companyName", type: "string" },
			{ name: "x", type: "uint8" },
			{ name: "y", type: "uint8" },
		],
		name: "placeCompany",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ name: "user", type: "address" }],
		name: "getUserPlacement",
		outputs: [
			{ name: "companyUrl", type: "string" },
			{ name: "companyName", type: "string" },
			{ name: "x", type: "uint8" },
			{ name: "y", type: "uint8" },
			{ name: "timestamp", type: "uint256" },
			{ name: "exists", type: "bool" },
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ name: "x", type: "uint8" },
			{ name: "y", type: "uint8" },
		],
		name: "getPlacementAtPosition",
		outputs: [
			{ name: "user", type: "address" },
			{ name: "companyUrl", type: "string" },
			{ name: "companyName", type: "string" },
			{ name: "timestamp", type: "uint256" },
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "getAllPlacements",
		outputs: [
			{ name: "users", type: "address[]" },
			{ name: "companyUrls", type: "string[]" },
			{ name: "companyNames", type: "string[]" },
			{ name: "xPositions", type: "uint8[]" },
			{ name: "yPositions", type: "uint8[]" },
			{ name: "timestamps", type: "uint256[]" },
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ name: "x", type: "uint8" },
			{ name: "y", type: "uint8" },
		],
		name: "isPositionAvailable",
		outputs: [{ name: "", type: "bool" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "getTotalPlacements",
		outputs: [{ name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "removePlacement",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "GRID_SIZE",
		outputs: [{ name: "", type: "uint8" }],
		stateMutability: "view",
		type: "function",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, name: "user", type: "address" },
			{ indexed: false, name: "companyUrl", type: "string" },
			{ indexed: false, name: "companyName", type: "string" },
			{ indexed: false, name: "x", type: "uint8" },
			{ indexed: false, name: "y", type: "uint8" },
			{ indexed: false, name: "timestamp", type: "uint256" },
		],
		name: "CompanyPlaced",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, name: "user", type: "address" },
			{ indexed: false, name: "oldUrl", type: "string" },
			{ indexed: false, name: "newUrl", type: "string" },
			{ indexed: false, name: "newCompanyName", type: "string" },
			{ indexed: false, name: "newX", type: "uint8" },
			{ indexed: false, name: "newY", type: "uint8" },
		],
		name: "CompanyUpdated",
		type: "event",
	},
] as const;
